server:
  port: 8080

spring:
  application:
    name: jay-showcase
  threads.virtual.enabled: true
  mvc.problemdetails.enabled: true

management:
  endpoints.web.exposure.include: health,info
  endpoint.health.show-details: always
